export const ENV_VARS = {
  //---DB Env---
  //Common
  DB_PORT: "DB_PORT",
  DB_USERNAME: "DB_USERNAME",
  DB_PASSWORD: "DB_PASSWORD",
  //Prod
  DB_PROD_HOST: "DB_PROD_HOST",
  DB_PROD_DATABASE: "DB_PROD_DATABASE",
  //Dev
  DB_DEV_HOST: "DB_DEV_HOST",
  DB_DEV_DATABASE: "DB_DEV_DATABASE",

  //---Google Api Env---
  LOCAL_GOOGLE_LOGIN_CB: "LOCAL_GOOGLE_LOGIN_CB",
  EC2_GOOGLE_LOGIN_CB: "EC2_GOOGLE_LOGIN_CB",
  GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID",
  GOOGLE_API_KEY: "GOOGLE_API_KEY",

  //---Aws Env---
  //Prod
  AWS_S3_REGION: "AWS_S3_REGION",
  AWS: "AWS",
  AWS_S3_DEPLOY_BUCKET_NAME: "AWS_S3_DEPLOY_BUCKET_NAME",
  AWS_S3_USER_PROFILES_BUCKET_NAME: "AWS_S3_USER_PROFILES_BUCKET_NAME",
  PROD_AWS_S3_ACCESS_KEY: "PROD_AWS_S3_ACCESS_KEY",
  PROD_AWS_S3_SECRET_KEY: "PROD_AWS_S3_SECRET_KEY",
  //Dev
  AWS_S3_USER_DEV_PROFILES_BUCKET_NAME: "AWS_S3_USER_DEV_PROFILES_BUCKET_NAME",
  DEV_AWS_S3_ACCESS_KEY: "DEV_AWS_S3_ACCESS_KEY",
  DEV_AWS_S3_SECRET_KEY: "DEV_AWS_S3_SECRET_KEY",

  //---Jwt Env---
  JWT_KEY: "JWT_KEY",
  JWT_EXPIRES: "JWT_EXPIRES",
  JWKS_URI: "JWKS_URI",
  ISSUER: "ISSUER",
  GOOGLE_WEB_CLIENT_ID: "GOOGLE_WEB_CLIENT_ID",
  GOOGLE_WEB_SECRET: "GOOGLE_WEB_SECRET",
  APPLE_TEAM_ID: "APPLE_TEAM_ID",
  APPLE_APP_KEY: "APPLE_APP_KEY",
  APPLE_CLIENT_ID: "APPLE_CLIENT_ID",

  //---Common Env---
  MODE: "MODE",
  LOCAL_IP: "LOCAL_IP",
  SEARCH_BOUNDARY: "SEARCH_BOUNDARY",

  //---Internal Env---
  PORT: "PORT",
  SWAGGER_USER: "SWAGGER_USER",
  SWAGGER_PASSWORD: "SWAGGER_PASSWORD",

  //---Redis Env----
  DEV_REDIS_URL: "DEV_REDIS_URL",
  PROD_REDIS_URL: "PROD_REDIS_URL",
  PROD_REDIS_PASSWORD: "PROD_REDIS_PASSWORD",
};
